-- MySQL Script generated by MySQL Workbench
-- Fri Jul 27 11:11:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Aplicacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Aplicacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aplicacion` DEFAULT CHARACTER SET utf8 ;
USE `Aplicacion` ;

-- -----------------------------------------------------
-- Table `Aplicacion`.`Estacionamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aplicacion`.`Estacionamientos` (
  `id_est` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `capacidad` INT(5) NOT NULL,
  `lugar` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_est`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
